//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AplicacaoForm.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectUsuarioUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoPAOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::AplicacaoForm.Properties.Settings.Default.Telas_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertUsuarioCompletedEventHandler InsertUsuarioCompleted;
        
        /// <remarks/>
        public event DeleteUsuarioCompletedEventHandler DeleteUsuarioCompleted;
        
        /// <remarks/>
        public event AlterarUsuarioCompletedEventHandler AlterarUsuarioCompleted;
        
        /// <remarks/>
        public event ListarUsuarioCompletedEventHandler ListarUsuarioCompleted;
        
        /// <remarks/>
        public event SelectUsuarioUsuarioCompletedEventHandler SelectUsuarioUsuarioCompleted;
        
        /// <remarks/>
        public event LogarUsuarioCompletedEventHandler LogarUsuarioCompleted;
        
        /// <remarks/>
        public event InserirServicoCompletedEventHandler InserirServicoCompleted;
        
        /// <remarks/>
        public event DeletarServicoCompletedEventHandler DeletarServicoCompleted;
        
        /// <remarks/>
        public event ListarServicoCompletedEventHandler ListarServicoCompleted;
        
        /// <remarks/>
        public event ListarServicoIDCompletedEventHandler ListarServicoIDCompleted;
        
        /// <remarks/>
        public event ListarServicoPACompletedEventHandler ListarServicoPACompleted;
        
        /// <remarks/>
        public event InserirContratoCompletedEventHandler InserirContratoCompleted;
        
        /// <remarks/>
        public event DeletarContratoCompletedEventHandler DeletarContratoCompleted;
        
        /// <remarks/>
        public event ListarContratoCompletedEventHandler ListarContratoCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("InsertUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(Usuario usuario) {
            this.InsertUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InsertUsuarioAsync(Usuario usuario, object userState) {
            if ((this.InsertUsuarioOperationCompleted == null)) {
                this.InsertUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertUsuario", new object[] {
                        usuario}, this.InsertUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertUsuarioOperationCompleted(object arg) {
            if ((this.InsertUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteUsuario(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            this.Invoke("DeleteUsuario", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
        }
        
        /// <remarks/>
        public void DeleteUsuarioAsync(int idUsuario, bool idUsuarioSpecified) {
            this.DeleteUsuarioAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteUsuarioAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.DeleteUsuarioOperationCompleted == null)) {
                this.DeleteUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteUsuarioOperationCompleted);
            }
            this.InvokeAsync("DeleteUsuario", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.DeleteUsuarioOperationCompleted, userState);
        }
        
        private void OnDeleteUsuarioOperationCompleted(object arg) {
            if ((this.DeleteUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Usuario usuario) {
            this.Invoke("AlterarUsuario", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario) {
            this.AlterarUsuarioAsync(usuario, null);
        }
        
        /// <remarks/>
        public void AlterarUsuarioAsync(Usuario usuario, object userState) {
            if ((this.AlterarUsuarioOperationCompleted == null)) {
                this.AlterarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioOperationCompleted);
            }
            this.InvokeAsync("AlterarUsuario", new object[] {
                        usuario}, this.AlterarUsuarioOperationCompleted, userState);
        }
        
        private void OnAlterarUsuarioOperationCompleted(object arg) {
            if ((this.AlterarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Usuario[] ListarUsuario() {
            object[] results = this.Invoke("ListarUsuario", new object[0]);
            return ((Usuario[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync() {
            this.ListarUsuarioAsync(null);
        }
        
        /// <remarks/>
        public void ListarUsuarioAsync(object userState) {
            if ((this.ListarUsuarioOperationCompleted == null)) {
                this.ListarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ListarUsuario", new object[0], this.ListarUsuarioOperationCompleted, userState);
        }
        
        private void OnListarUsuarioOperationCompleted(object arg) {
            if ((this.ListarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarUsuarioCompleted(this, new ListarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectUsuarioUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario SelectUsuarioUsuario(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("SelectUsuarioUsuario", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void SelectUsuarioUsuarioAsync(int idUsuario, bool idUsuarioSpecified) {
            this.SelectUsuarioUsuarioAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void SelectUsuarioUsuarioAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.SelectUsuarioUsuarioOperationCompleted == null)) {
                this.SelectUsuarioUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectUsuarioUsuarioOperationCompleted);
            }
            this.InvokeAsync("SelectUsuarioUsuario", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.SelectUsuarioUsuarioOperationCompleted, userState);
        }
        
        private void OnSelectUsuarioUsuarioOperationCompleted(object arg) {
            if ((this.SelectUsuarioUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectUsuarioUsuarioCompleted(this, new SelectUsuarioUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LogarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Usuario LogarUsuario([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senha) {
            object[] results = this.Invoke("LogarUsuario", new object[] {
                        emial,
                        senha});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void LogarUsuarioAsync(string emial, string senha) {
            this.LogarUsuarioAsync(emial, senha, null);
        }
        
        /// <remarks/>
        public void LogarUsuarioAsync(string emial, string senha, object userState) {
            if ((this.LogarUsuarioOperationCompleted == null)) {
                this.LogarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogarUsuarioOperationCompleted);
            }
            this.InvokeAsync("LogarUsuario", new object[] {
                        emial,
                        senha}, this.LogarUsuarioOperationCompleted, userState);
        }
        
        private void OnLogarUsuarioOperationCompleted(object arg) {
            if ((this.LogarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogarUsuarioCompleted(this, new LogarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirServico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Servico servico) {
            this.Invoke("InserirServico", new object[] {
                        servico});
        }
        
        /// <remarks/>
        public void InserirServicoAsync(Servico servico) {
            this.InserirServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void InserirServicoAsync(Servico servico, object userState) {
            if ((this.InserirServicoOperationCompleted == null)) {
                this.InserirServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirServicoOperationCompleted);
            }
            this.InvokeAsync("InserirServico", new object[] {
                        servico}, this.InserirServicoOperationCompleted, userState);
        }
        
        private void OnInserirServicoOperationCompleted(object arg) {
            if ((this.InserirServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarServico(int idServico, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idServicoSpecified) {
            this.Invoke("DeletarServico", new object[] {
                        idServico,
                        idServicoSpecified});
        }
        
        /// <remarks/>
        public void DeletarServicoAsync(int idServico, bool idServicoSpecified) {
            this.DeletarServicoAsync(idServico, idServicoSpecified, null);
        }
        
        /// <remarks/>
        public void DeletarServicoAsync(int idServico, bool idServicoSpecified, object userState) {
            if ((this.DeletarServicoOperationCompleted == null)) {
                this.DeletarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarServicoOperationCompleted);
            }
            this.InvokeAsync("DeletarServico", new object[] {
                        idServico,
                        idServicoSpecified}, this.DeletarServicoOperationCompleted, userState);
        }
        
        private void OnDeletarServicoOperationCompleted(object arg) {
            if ((this.DeletarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServico() {
            object[] results = this.Invoke("ListarServico", new object[0]);
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoAsync() {
            this.ListarServicoAsync(null);
        }
        
        /// <remarks/>
        public void ListarServicoAsync(object userState) {
            if ((this.ListarServicoOperationCompleted == null)) {
                this.ListarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoOperationCompleted);
            }
            this.InvokeAsync("ListarServico", new object[0], this.ListarServicoOperationCompleted, userState);
        }
        
        private void OnListarServicoOperationCompleted(object arg) {
            if ((this.ListarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoCompleted(this, new ListarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServicoID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServicoID(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("ListarServicoID", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoIDAsync(int idUsuario, bool idUsuarioSpecified) {
            this.ListarServicoIDAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void ListarServicoIDAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.ListarServicoIDOperationCompleted == null)) {
                this.ListarServicoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoIDOperationCompleted);
            }
            this.InvokeAsync("ListarServicoID", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.ListarServicoIDOperationCompleted, userState);
        }
        
        private void OnListarServicoIDOperationCompleted(object arg) {
            if ((this.ListarServicoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoIDCompleted(this, new ListarServicoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServicoPA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServicoPA([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parametro) {
            object[] results = this.Invoke("ListarServicoPA", new object[] {
                        parametro});
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoPAAsync(string parametro) {
            this.ListarServicoPAAsync(parametro, null);
        }
        
        /// <remarks/>
        public void ListarServicoPAAsync(string parametro, object userState) {
            if ((this.ListarServicoPAOperationCompleted == null)) {
                this.ListarServicoPAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoPAOperationCompleted);
            }
            this.InvokeAsync("ListarServicoPA", new object[] {
                        parametro}, this.ListarServicoPAOperationCompleted, userState);
        }
        
        private void OnListarServicoPAOperationCompleted(object arg) {
            if ((this.ListarServicoPACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoPACompleted(this, new ListarServicoPACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirContrato([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Contrato contrato) {
            this.Invoke("InserirContrato", new object[] {
                        contrato});
        }
        
        /// <remarks/>
        public void InserirContratoAsync(Contrato contrato) {
            this.InserirContratoAsync(contrato, null);
        }
        
        /// <remarks/>
        public void InserirContratoAsync(Contrato contrato, object userState) {
            if ((this.InserirContratoOperationCompleted == null)) {
                this.InserirContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirContratoOperationCompleted);
            }
            this.InvokeAsync("InserirContrato", new object[] {
                        contrato}, this.InserirContratoOperationCompleted, userState);
        }
        
        private void OnInserirContratoOperationCompleted(object arg) {
            if ((this.InserirContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirContratoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarContrato(int idContrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idContratoSpecified) {
            this.Invoke("DeletarContrato", new object[] {
                        idContrato,
                        idContratoSpecified});
        }
        
        /// <remarks/>
        public void DeletarContratoAsync(int idContrato, bool idContratoSpecified) {
            this.DeletarContratoAsync(idContrato, idContratoSpecified, null);
        }
        
        /// <remarks/>
        public void DeletarContratoAsync(int idContrato, bool idContratoSpecified, object userState) {
            if ((this.DeletarContratoOperationCompleted == null)) {
                this.DeletarContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarContratoOperationCompleted);
            }
            this.InvokeAsync("DeletarContrato", new object[] {
                        idContrato,
                        idContratoSpecified}, this.DeletarContratoOperationCompleted, userState);
        }
        
        private void OnDeletarContratoOperationCompleted(object arg) {
            if ((this.DeletarContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarContratoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Contrato[] ListarContrato(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("ListarContrato", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Contrato[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContratoAsync(int idUsuario, bool idUsuarioSpecified) {
            this.ListarContratoAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void ListarContratoAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.ListarContratoOperationCompleted == null)) {
                this.ListarContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContratoOperationCompleted);
            }
            this.InvokeAsync("ListarContrato", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.ListarContratoOperationCompleted, userState);
        }
        
        private void OnListarContratoOperationCompleted(object arg) {
            if ((this.ListarContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContratoCompleted(this, new ListarContratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Usuario {
        
        private string emailField;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nomeField;
        
        private string senhaField;
        
        private int telefoneField;
        
        private bool telefoneFieldSpecified;
        
        private string tipoAcessoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public int Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TelefoneSpecified {
            get {
                return this.telefoneFieldSpecified;
            }
            set {
                this.telefoneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoAcesso {
            get {
                return this.tipoAcessoField;
            }
            set {
                this.tipoAcessoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AplicacaoServidor")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Contrato {
        
        private string empresaField;
        
        private int idcontratoField;
        
        private bool idcontratoFieldSpecified;
        
        private int idservicoField;
        
        private int idusuarioField;
        
        private string nomeField;
        
        private string tipoField;
        
        private int valorField;
        
        private bool valorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
        
        /// <remarks/>
        public int Idcontrato {
            get {
                return this.idcontratoField;
            }
            set {
                this.idcontratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdcontratoSpecified {
            get {
                return this.idcontratoFieldSpecified;
            }
            set {
                this.idcontratoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Idservico {
            get {
                return this.idservicoField;
            }
            set {
                this.idservicoField = value;
            }
        }
        
        /// <remarks/>
        public int Idusuario {
            get {
                return this.idusuarioField;
            }
            set {
                this.idusuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Servico {
        
        private int idServicoField;
        
        private bool idServicoFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string nomeField;
        
        private string tipoServicoField;
        
        private int valorField;
        
        private bool valorFieldSpecified;
        
        /// <remarks/>
        public int IdServico {
            get {
                return this.idServicoField;
            }
            set {
                this.idServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdServicoSpecified {
            get {
                return this.idServicoFieldSpecified;
            }
            set {
                this.idServicoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                this.tipoServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InsertUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AlterarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarUsuarioCompletedEventHandler(object sender, ListarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectUsuarioUsuarioCompletedEventHandler(object sender, SelectUsuarioUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectUsuarioUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectUsuarioUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LogarUsuarioCompletedEventHandler(object sender, LogarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InserirServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeletarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoCompletedEventHandler(object sender, ListarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoIDCompletedEventHandler(object sender, ListarServicoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoPACompletedEventHandler(object sender, ListarServicoPACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoPACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoPACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InserirContratoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeletarContratoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarContratoCompletedEventHandler(object sender, ListarContratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contrato[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contrato[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591