//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AplicacaoForm.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarServicoPAOperationCompleted;
        
        private System.Threading.SendOrPostCallback InserirContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarContratoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContratoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::AplicacaoForm.Properties.Settings.Default.Telas_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertClienteCompletedEventHandler InsertClienteCompleted;
        
        /// <remarks/>
        public event DeleteClienteCompletedEventHandler DeleteClienteCompleted;
        
        /// <remarks/>
        public event AlterarClienteCompletedEventHandler AlterarClienteCompleted;
        
        /// <remarks/>
        public event ListarClienteCompletedEventHandler ListarClienteCompleted;
        
        /// <remarks/>
        public event SelectClienteCompletedEventHandler SelectClienteCompleted;
        
        /// <remarks/>
        public event LogarClienteCompletedEventHandler LogarClienteCompleted;
        
        /// <remarks/>
        public event InsertEmpresaCompletedEventHandler InsertEmpresaCompleted;
        
        /// <remarks/>
        public event DeleteEmpresaCompletedEventHandler DeleteEmpresaCompleted;
        
        /// <remarks/>
        public event AlterarEmpresaCompletedEventHandler AlterarEmpresaCompleted;
        
        /// <remarks/>
        public event ListarEmpresaCompletedEventHandler ListarEmpresaCompleted;
        
        /// <remarks/>
        public event SelectEmpresaCompletedEventHandler SelectEmpresaCompleted;
        
        /// <remarks/>
        public event LogarEmpresaCompletedEventHandler LogarEmpresaCompleted;
        
        /// <remarks/>
        public event InserirServicoCompletedEventHandler InserirServicoCompleted;
        
        /// <remarks/>
        public event DeletarServicoCompletedEventHandler DeletarServicoCompleted;
        
        /// <remarks/>
        public event SelectServicoCompletedEventHandler SelectServicoCompleted;
        
        /// <remarks/>
        public event ListarServicoCompletedEventHandler ListarServicoCompleted;
        
        /// <remarks/>
        public event ListarServicoIDCompletedEventHandler ListarServicoIDCompleted;
        
        /// <remarks/>
        public event ListarServicoPACompletedEventHandler ListarServicoPACompleted;
        
        /// <remarks/>
        public event InserirContratoCompletedEventHandler InserirContratoCompleted;
        
        /// <remarks/>
        public event DeletarContratoCompletedEventHandler DeletarContratoCompleted;
        
        /// <remarks/>
        public event ListarContratoCompletedEventHandler ListarContratoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente usuario) {
            this.Invoke("InsertCliente", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void InsertClienteAsync(Cliente usuario) {
            this.InsertClienteAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InsertClienteAsync(Cliente usuario, object userState) {
            if ((this.InsertClienteOperationCompleted == null)) {
                this.InsertClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertClienteOperationCompleted);
            }
            this.InvokeAsync("InsertCliente", new object[] {
                        usuario}, this.InsertClienteOperationCompleted, userState);
        }
        
        private void OnInsertClienteOperationCompleted(object arg) {
            if ((this.InsertClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCliente(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            this.Invoke("DeleteCliente", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
        }
        
        /// <remarks/>
        public void DeleteClienteAsync(int idUsuario, bool idUsuarioSpecified) {
            this.DeleteClienteAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteClienteAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.DeleteClienteOperationCompleted == null)) {
                this.DeleteClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteClienteOperationCompleted);
            }
            this.InvokeAsync("DeleteCliente", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.DeleteClienteOperationCompleted, userState);
        }
        
        private void OnDeleteClienteOperationCompleted(object arg) {
            if ((this.DeleteClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Cliente usuario, bool emailAtual, [System.Xml.Serialization.XmlIgnoreAttribute()] bool emailAtualSpecified) {
            this.Invoke("AlterarCliente", new object[] {
                        usuario,
                        emailAtual,
                        emailAtualSpecified});
        }
        
        /// <remarks/>
        public void AlterarClienteAsync(Cliente usuario, bool emailAtual, bool emailAtualSpecified) {
            this.AlterarClienteAsync(usuario, emailAtual, emailAtualSpecified, null);
        }
        
        /// <remarks/>
        public void AlterarClienteAsync(Cliente usuario, bool emailAtual, bool emailAtualSpecified, object userState) {
            if ((this.AlterarClienteOperationCompleted == null)) {
                this.AlterarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarClienteOperationCompleted);
            }
            this.InvokeAsync("AlterarCliente", new object[] {
                        usuario,
                        emailAtual,
                        emailAtualSpecified}, this.AlterarClienteOperationCompleted, userState);
        }
        
        private void OnAlterarClienteOperationCompleted(object arg) {
            if ((this.AlterarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Cliente[] ListarCliente() {
            object[] results = this.Invoke("ListarCliente", new object[0]);
            return ((Cliente[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarClienteAsync() {
            this.ListarClienteAsync(null);
        }
        
        /// <remarks/>
        public void ListarClienteAsync(object userState) {
            if ((this.ListarClienteOperationCompleted == null)) {
                this.ListarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarClienteOperationCompleted);
            }
            this.InvokeAsync("ListarCliente", new object[0], this.ListarClienteOperationCompleted, userState);
        }
        
        private void OnListarClienteOperationCompleted(object arg) {
            if ((this.ListarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarClienteCompleted(this, new ListarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente SelectCliente(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("SelectCliente", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void SelectClienteAsync(int idUsuario, bool idUsuarioSpecified) {
            this.SelectClienteAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void SelectClienteAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.SelectClienteOperationCompleted == null)) {
                this.SelectClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectClienteOperationCompleted);
            }
            this.InvokeAsync("SelectCliente", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.SelectClienteOperationCompleted, userState);
        }
        
        private void OnSelectClienteOperationCompleted(object arg) {
            if ((this.SelectClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectClienteCompleted(this, new SelectClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LogarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente LogarCliente([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senha) {
            object[] results = this.Invoke("LogarCliente", new object[] {
                        emial,
                        senha});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void LogarClienteAsync(string emial, string senha) {
            this.LogarClienteAsync(emial, senha, null);
        }
        
        /// <remarks/>
        public void LogarClienteAsync(string emial, string senha, object userState) {
            if ((this.LogarClienteOperationCompleted == null)) {
                this.LogarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogarClienteOperationCompleted);
            }
            this.InvokeAsync("LogarCliente", new object[] {
                        emial,
                        senha}, this.LogarClienteOperationCompleted, userState);
        }
        
        private void OnLogarClienteOperationCompleted(object arg) {
            if ((this.LogarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogarClienteCompleted(this, new LogarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InsertEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertEmpresa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Empresa usuario) {
            this.Invoke("InsertEmpresa", new object[] {
                        usuario});
        }
        
        /// <remarks/>
        public void InsertEmpresaAsync(Empresa usuario) {
            this.InsertEmpresaAsync(usuario, null);
        }
        
        /// <remarks/>
        public void InsertEmpresaAsync(Empresa usuario, object userState) {
            if ((this.InsertEmpresaOperationCompleted == null)) {
                this.InsertEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertEmpresaOperationCompleted);
            }
            this.InvokeAsync("InsertEmpresa", new object[] {
                        usuario}, this.InsertEmpresaOperationCompleted, userState);
        }
        
        private void OnInsertEmpresaOperationCompleted(object arg) {
            if ((this.InsertEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeleteEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteEmpresa(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            this.Invoke("DeleteEmpresa", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
        }
        
        /// <remarks/>
        public void DeleteEmpresaAsync(int idUsuario, bool idUsuarioSpecified) {
            this.DeleteEmpresaAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void DeleteEmpresaAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.DeleteEmpresaOperationCompleted == null)) {
                this.DeleteEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmpresaOperationCompleted);
            }
            this.InvokeAsync("DeleteEmpresa", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.DeleteEmpresaOperationCompleted, userState);
        }
        
        private void OnDeleteEmpresaOperationCompleted(object arg) {
            if ((this.DeleteEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/AlterarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarEmpresa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Empresa usuario, bool emailAtual, [System.Xml.Serialization.XmlIgnoreAttribute()] bool emailAtualSpecified) {
            this.Invoke("AlterarEmpresa", new object[] {
                        usuario,
                        emailAtual,
                        emailAtualSpecified});
        }
        
        /// <remarks/>
        public void AlterarEmpresaAsync(Empresa usuario, bool emailAtual, bool emailAtualSpecified) {
            this.AlterarEmpresaAsync(usuario, emailAtual, emailAtualSpecified, null);
        }
        
        /// <remarks/>
        public void AlterarEmpresaAsync(Empresa usuario, bool emailAtual, bool emailAtualSpecified, object userState) {
            if ((this.AlterarEmpresaOperationCompleted == null)) {
                this.AlterarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarEmpresaOperationCompleted);
            }
            this.InvokeAsync("AlterarEmpresa", new object[] {
                        usuario,
                        emailAtual,
                        emailAtualSpecified}, this.AlterarEmpresaOperationCompleted, userState);
        }
        
        private void OnAlterarEmpresaOperationCompleted(object arg) {
            if ((this.AlterarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Empresa[] ListarEmpresa() {
            object[] results = this.Invoke("ListarEmpresa", new object[0]);
            return ((Empresa[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync() {
            this.ListarEmpresaAsync(null);
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync(object userState) {
            if ((this.ListarEmpresaOperationCompleted == null)) {
                this.ListarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmpresaOperationCompleted);
            }
            this.InvokeAsync("ListarEmpresa", new object[0], this.ListarEmpresaOperationCompleted, userState);
        }
        
        private void OnListarEmpresaOperationCompleted(object arg) {
            if ((this.ListarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmpresaCompleted(this, new ListarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Empresa SelectEmpresa(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("SelectEmpresa", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Empresa)(results[0]));
        }
        
        /// <remarks/>
        public void SelectEmpresaAsync(int idUsuario, bool idUsuarioSpecified) {
            this.SelectEmpresaAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void SelectEmpresaAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.SelectEmpresaOperationCompleted == null)) {
                this.SelectEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectEmpresaOperationCompleted);
            }
            this.InvokeAsync("SelectEmpresa", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.SelectEmpresaOperationCompleted, userState);
        }
        
        private void OnSelectEmpresaOperationCompleted(object arg) {
            if ((this.SelectEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectEmpresaCompleted(this, new SelectEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/LogarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Empresa LogarEmpresa([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string emial, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senha) {
            object[] results = this.Invoke("LogarEmpresa", new object[] {
                        emial,
                        senha});
            return ((Empresa)(results[0]));
        }
        
        /// <remarks/>
        public void LogarEmpresaAsync(string emial, string senha) {
            this.LogarEmpresaAsync(emial, senha, null);
        }
        
        /// <remarks/>
        public void LogarEmpresaAsync(string emial, string senha, object userState) {
            if ((this.LogarEmpresaOperationCompleted == null)) {
                this.LogarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogarEmpresaOperationCompleted);
            }
            this.InvokeAsync("LogarEmpresa", new object[] {
                        emial,
                        senha}, this.LogarEmpresaOperationCompleted, userState);
        }
        
        private void OnLogarEmpresaOperationCompleted(object arg) {
            if ((this.LogarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogarEmpresaCompleted(this, new LogarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirServico([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Servico servico) {
            this.Invoke("InserirServico", new object[] {
                        servico});
        }
        
        /// <remarks/>
        public void InserirServicoAsync(Servico servico) {
            this.InserirServicoAsync(servico, null);
        }
        
        /// <remarks/>
        public void InserirServicoAsync(Servico servico, object userState) {
            if ((this.InserirServicoOperationCompleted == null)) {
                this.InserirServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirServicoOperationCompleted);
            }
            this.InvokeAsync("InserirServico", new object[] {
                        servico}, this.InserirServicoOperationCompleted, userState);
        }
        
        private void OnInserirServicoOperationCompleted(object arg) {
            if ((this.InserirServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarServico(int idServico, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idServicoSpecified) {
            this.Invoke("DeletarServico", new object[] {
                        idServico,
                        idServicoSpecified});
        }
        
        /// <remarks/>
        public void DeletarServicoAsync(int idServico, bool idServicoSpecified) {
            this.DeletarServicoAsync(idServico, idServicoSpecified, null);
        }
        
        /// <remarks/>
        public void DeletarServicoAsync(int idServico, bool idServicoSpecified, object userState) {
            if ((this.DeletarServicoOperationCompleted == null)) {
                this.DeletarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarServicoOperationCompleted);
            }
            this.InvokeAsync("DeletarServico", new object[] {
                        idServico,
                        idServicoSpecified}, this.DeletarServicoOperationCompleted, userState);
        }
        
        private void OnDeletarServicoOperationCompleted(object arg) {
            if ((this.DeletarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarServicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/SelectServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Servico SelectServico(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("SelectServico", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Servico)(results[0]));
        }
        
        /// <remarks/>
        public void SelectServicoAsync(int idUsuario, bool idUsuarioSpecified) {
            this.SelectServicoAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void SelectServicoAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.SelectServicoOperationCompleted == null)) {
                this.SelectServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectServicoOperationCompleted);
            }
            this.InvokeAsync("SelectServico", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.SelectServicoOperationCompleted, userState);
        }
        
        private void OnSelectServicoOperationCompleted(object arg) {
            if ((this.SelectServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectServicoCompleted(this, new SelectServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServico() {
            object[] results = this.Invoke("ListarServico", new object[0]);
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoAsync() {
            this.ListarServicoAsync(null);
        }
        
        /// <remarks/>
        public void ListarServicoAsync(object userState) {
            if ((this.ListarServicoOperationCompleted == null)) {
                this.ListarServicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoOperationCompleted);
            }
            this.InvokeAsync("ListarServico", new object[0], this.ListarServicoOperationCompleted, userState);
        }
        
        private void OnListarServicoOperationCompleted(object arg) {
            if ((this.ListarServicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoCompleted(this, new ListarServicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServicoID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServicoID(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("ListarServicoID", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoIDAsync(int idUsuario, bool idUsuarioSpecified) {
            this.ListarServicoIDAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void ListarServicoIDAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.ListarServicoIDOperationCompleted == null)) {
                this.ListarServicoIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoIDOperationCompleted);
            }
            this.InvokeAsync("ListarServicoID", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.ListarServicoIDOperationCompleted, userState);
        }
        
        private void OnListarServicoIDOperationCompleted(object arg) {
            if ((this.ListarServicoIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoIDCompleted(this, new ListarServicoIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarServicoPA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Servico[] ListarServicoPA([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string parametro) {
            object[] results = this.Invoke("ListarServicoPA", new object[] {
                        parametro});
            return ((Servico[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarServicoPAAsync(string parametro) {
            this.ListarServicoPAAsync(parametro, null);
        }
        
        /// <remarks/>
        public void ListarServicoPAAsync(string parametro, object userState) {
            if ((this.ListarServicoPAOperationCompleted == null)) {
                this.ListarServicoPAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarServicoPAOperationCompleted);
            }
            this.InvokeAsync("ListarServicoPA", new object[] {
                        parametro}, this.ListarServicoPAOperationCompleted, userState);
        }
        
        private void OnListarServicoPAOperationCompleted(object arg) {
            if ((this.ListarServicoPACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarServicoPACompleted(this, new ListarServicoPACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/InserirContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InserirContrato([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Contrato contrato) {
            this.Invoke("InserirContrato", new object[] {
                        contrato});
        }
        
        /// <remarks/>
        public void InserirContratoAsync(Contrato contrato) {
            this.InserirContratoAsync(contrato, null);
        }
        
        /// <remarks/>
        public void InserirContratoAsync(Contrato contrato, object userState) {
            if ((this.InserirContratoOperationCompleted == null)) {
                this.InserirContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInserirContratoOperationCompleted);
            }
            this.InvokeAsync("InserirContrato", new object[] {
                        contrato}, this.InserirContratoOperationCompleted, userState);
        }
        
        private void OnInserirContratoOperationCompleted(object arg) {
            if ((this.InserirContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InserirContratoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/DeletarContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarContrato(int idContrato, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idContratoSpecified) {
            this.Invoke("DeletarContrato", new object[] {
                        idContrato,
                        idContratoSpecified});
        }
        
        /// <remarks/>
        public void DeletarContratoAsync(int idContrato, bool idContratoSpecified) {
            this.DeletarContratoAsync(idContrato, idContratoSpecified, null);
        }
        
        /// <remarks/>
        public void DeletarContratoAsync(int idContrato, bool idContratoSpecified, object userState) {
            if ((this.DeletarContratoOperationCompleted == null)) {
                this.DeletarContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarContratoOperationCompleted);
            }
            this.InvokeAsync("DeletarContrato", new object[] {
                        idContrato,
                        idContratoSpecified}, this.DeletarContratoOperationCompleted, userState);
        }
        
        private void OnDeletarContratoOperationCompleted(object arg) {
            if ((this.DeletarContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarContratoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/ListarContrato", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
        public Contrato[] ListarContrato(int idUsuario, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idUsuarioSpecified) {
            object[] results = this.Invoke("ListarContrato", new object[] {
                        idUsuario,
                        idUsuarioSpecified});
            return ((Contrato[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContratoAsync(int idUsuario, bool idUsuarioSpecified) {
            this.ListarContratoAsync(idUsuario, idUsuarioSpecified, null);
        }
        
        /// <remarks/>
        public void ListarContratoAsync(int idUsuario, bool idUsuarioSpecified, object userState) {
            if ((this.ListarContratoOperationCompleted == null)) {
                this.ListarContratoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContratoOperationCompleted);
            }
            this.InvokeAsync("ListarContrato", new object[] {
                        idUsuario,
                        idUsuarioSpecified}, this.ListarContratoOperationCompleted, userState);
        }
        
        private void OnListarContratoOperationCompleted(object arg) {
            if ((this.ListarContratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContratoCompleted(this, new ListarContratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Cliente {
        
        private string emailField;
        
        private int idUsuarioField;
        
        private string nomeField;
        
        private string senhaField;
        
        private int telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public int Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Contrato {
        
        private Cliente entClienteField;
        
        private Servico entServicoField;
        
        private int idcontratoField;
        
        private string nomeEmpresaField;
        
        private string nomeServicoField;
        
        private string tipoServicoField;
        
        private int valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Cliente EntCliente {
            get {
                return this.entClienteField;
            }
            set {
                this.entClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Servico EntServico {
            get {
                return this.entServicoField;
            }
            set {
                this.entServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Idcontrato {
            get {
                return this.idcontratoField;
            }
            set {
                this.idcontratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomeEmpresa {
            get {
                return this.nomeEmpresaField;
            }
            set {
                this.nomeEmpresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NomeServico {
            get {
                return this.nomeServicoField;
            }
            set {
                this.nomeServicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                this.tipoServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Servico {
        
        private Empresa entEmpresaField;
        
        private int idServicoField;
        
        private int idUsuarioField;
        
        private string nomeField;
        
        private string tipoServicoField;
        
        private int valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Empresa EntEmpresa {
            get {
                return this.entEmpresaField;
            }
            set {
                this.entEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public int IdServico {
            get {
                return this.idServicoField;
            }
            set {
                this.idServicoField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TipoServico {
            get {
                return this.tipoServicoField;
            }
            set {
                this.tipoServicoField = value;
            }
        }
        
        /// <remarks/>
        public int Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Biblioteca.Negocio.Basica")]
    public partial class Empresa {
        
        private string emailField;
        
        private int idUsuarioField;
        
        private string nomeField;
        
        private string senhaField;
        
        private int telefoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public int Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InsertClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AlterarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarClienteCompletedEventHandler(object sender, ListarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectClienteCompletedEventHandler(object sender, SelectClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LogarClienteCompletedEventHandler(object sender, LogarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InsertEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeleteEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AlterarEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarEmpresaCompletedEventHandler(object sender, ListarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectEmpresaCompletedEventHandler(object sender, SelectEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LogarEmpresaCompletedEventHandler(object sender, LogarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InserirServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeletarServicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectServicoCompletedEventHandler(object sender, SelectServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoCompletedEventHandler(object sender, ListarServicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoIDCompletedEventHandler(object sender, ListarServicoIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarServicoPACompletedEventHandler(object sender, ListarServicoPACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarServicoPACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarServicoPACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Servico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Servico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void InserirContratoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void DeletarContratoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ListarContratoCompletedEventHandler(object sender, ListarContratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Contrato[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Contrato[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591